name: Photo Gallery CI
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Source Checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Buildx Image Build and Push
        run: |
          ./image-builder.sh
        env:
          DOCKER_REPO: hferentschik
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

